### ISSUE TITLE
Timing out when making http requests to quovo

### ISSUE THREAD

**Issue by summera** [studentloanbenefits/quovo-ruby#1]
@singjsong are you experiencing timeouts when attempting to make requests to 
Quovo with this gem or any other ruby http clients? Things are working fine for me when using Curl but this gem and manually just making requests via Net HTTP and other ruby clients are timing out for me.

**Comment by summera** [comment]
May have been the internet connection I was on before, but things are working now 🤷‍♂️ . Sorry for the false alarm.

**Comment by jhaber1** [comment]
No problem. Could also have been Quovo too, I've gotten timeouts with them in the past.
